# Generated by Django 3.0.9 on 2020-11-23 15:51

from django.db import migrations, models

def remove_old_settings(app, schema_editor):
    EventSettingsStore = app.get_model('pretixbase', 'Event_SettingsStore')

    EventSettingsStore.objects.filter(key__startswith='payment_', key__endswith='__hidden_url').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0174_merge_20201222_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ItemVariation',
            name='original_price',
            field=models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ItemVariation',
            name='default_price',
            field=models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='SubEventItem',
            name='price',
            field=models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='SubEventItemVariation',
            name='price',
            field=models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='Item',
            name='default_price',
            field=models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='Item',
            name='original_price',
            field=models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True),
        ),
    ]
